#!/bin/sh
echo "adding jira id"
COMMIT_FILE=$1
COMMIT_MSG=$(cat $1)
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
JIRA_ID=$(echo "$CURRENT_BRANCH" | grep -Eo "[A-Z0-9]{1,10}-?[A-Z0-9]+-\d+")
#JIRA_ID = $JIRA_ID_ENV
if [ ! -z "$JIRA_ID" ]; then
    if [[ $COMMIT_MSG =~ ^\[?$JIRA_ID\]? ]]; then
        echo "JIRA ID '$JIRA_ID', matched in current branch, is found in the commit message. Committing as is."
    else
        echo "[$JIRA_ID] $COMMIT_MSG" > $COMMIT_FILE
        echo "JIRA ID '$JIRA_ID', matched in current branch, prepended to commit message. (Use --no-verify to skip)"
    fi
fi
echo "done"
