config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_st-0.8.2:
    src: st-0.8.2
    dst: ~/st-0.8.2
  d_aliases.d:
    src: local/aliases.d
    dst: ~/.local/aliases.d
  d_bashrc.d:
    src: local/bashrc.d
    dst: ~/.local/bashrc.d
  d_profile.d:
    src: local/profile.d
    dst: ~/.local/profile.d
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_conkyrc:
    src: conkyrc
    dst: ~/.conkyrc
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  d_i3blocks:
    src: config/i3blocks
    dst: ~/.config/i3blocks
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_ipython:
    src: ipython
    dst: ~/.ipython
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_tmux.conf.local:
    src: tmux.conf.local
    dst: ~/.tmux.conf.local
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_ipython_config.py:
    src: ipython/profile_default/ipython_config.py
    dst: ~/.ipython/profile_default/ipython_config.py
  f_01-keybindings.py:
    src: ipython/profile_default/startup/01-keybindings.py
    dst: ~/.ipython/profile_default/startup/01-keybindings.py
  f_config.h:
    src: st-0.8.2/config.h
    dst: ~/st-0.8.2/config.h
  d_startup:
    src: ipython/profile_default/startup
    dst: ~/.ipython/profile_default/startup
  f_pdbrc.py:
    src: pdbrc.py
    dst: ~/.pdbrc.py
profiles:
  eliot:
    dotfiles:
    - d_st-0.8.2
    - d_aliases.d
    - d_bashrc.d
    - d_profile.d
    - f_bashrc
    - f_bash_profile
    - f_conkyrc
    - f_config
    - d_i3blocks
    - d_nvim
    - d_ipython
    - f_rc.conf
    - f_tmux.conf
    - f_xinitrc
    - f_xresources
  eva:
    dotfiles:
    - d_st-0.8.2
    - d_aliases.d
    - d_bashrc.d
    - d_profile.d
    - f_bashrc
    - f_bash_profile
    - f_config
    - d_nvim
    - d_ipython
    - f_rc.conf
    - f_tmux.conf
    - f_xinitrc
    - f_xmodmap
    - f_gitconfig
    - f_tmux.conf.local
    - f_init.vim
    - f_ipython_config.py
    - f_01-keybindings.py
    - f_config.h
    - d_startup
    - f_pdbrc.py
