config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_aliases.d:
    src: local/aliases.d
    dst: ~/.local/aliases.d
  d_bashrc.d:
    src: local/bashrc.d
    dst: ~/.local/bashrc.d
  d_profile.d:
    src: local/profile.d
    dst: ~/.local/profile.d
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_conkyrc:
    src: conkyrc
    dst: ~/.conkyrc
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  d_i3blocks:
    src: config/i3blocks
    dst: ~/.config/i3blocks
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    cmpignore:
      - "*/plugin"
    upignore:
      - "*/plugin"
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
    chmod: "644"
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_tmux.conf.local:
    src: tmux.conf.local
    dst: ~/.tmux.conf.local
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_ipython_config.py:
    src: ipython/profile_default/ipython_config.py
    dst: ~/.ipython/profile_default/ipython_config.py
  d_startup:
    src: ipython/profile_default/startup
    dst: ~/.ipython/profile_default/startup
  f_pdbrc.py:
    src: pdbrc.py
    dst: ~/.pdbrc.py
  f_fonts.conf:
    src: config/fontconfig/fonts.conf
    dst: ~/.config/fontconfig/fonts.conf
  d_git_template:
    src: git_template
    dst: ~/.git_template
  d_hooks:
    src: git_template/hooks
    dst: ~/.git_template/hooks
  f_fzf:
    src: fzf
    dst: ~/.fzf
  f_fzf.bash:
    src: fzf.bash
    dst: ~/.fzf.bash
  f_102.forgit.sh:
    src: local/profile.d/102.forgit.sh
    dst: ~/.local/profile.d/102.forgit.sh
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
  f_user.json:
    src: config/exercism/user.json
    dst: ~/.config/exercism/user.json
  f_test.json:
    src: config/karabiner/assets/complex_modifications/test.json
    dst: ~/.config/karabiner/assets/complex_modifications/test.json
  f_bashrc.remote:
    src: local/bashrc.remote
    dst: ~/.local/bashrc.remote
  d_tridactyl:
    src: config/tridactyl
    dst: ~/.config/tridactyl
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_ankirc:
    src: config/Ankirc
    dst: ~/.config/Ankirc
    chmod: "600"
  f_exercism_user.json:
    src: config/exercism/user.json
    dst: ~/.config/exercism/user.json
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  f_colorscheme:
    src: colorscheme
    dst: ~/.colorscheme
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  f_70-synaptics.conf:
    src: etc/X11/xorg.conf.d/70-synaptics.conf
    dst: /etc/X11/xorg.conf.d/70-synaptics.conf
  f_pam_env.conf:
    src: etc/security/pam_env.conf
    dst: /etc/security/pam_env.conf
  f_coc.vim:
    src: config/nvim/coc.vim
    dst: ~/.config/nvim/coc.vim
  d_lua:
    src: config/nvim/lua
    dst: ~/.config/nvim/lua
  f_coc-settings.json:
    src: config/nvim/coc-settings.json
    dst: ~/.config/nvim/coc-settings.json
  f_envrc.default:
    src: envrc.default
    dst: ~/envrc.default
  d_direnv:
    src: config/direnv
    dst: ~/.config/direnv
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_azote:
    src: config/azote
    dst: ~/.config/azote
  d_gh:
    src: config/gh
    dst: ~/.config/gh
    chmod: "751"
  d_gnome-session:
    src: config/gnome-session
    dst: ~/.config/gnome-session
    chmod: "700"
  d_goa-1.0:
    src: config/goa-1.0
    dst: ~/.config/goa-1.0
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: "700"
  d_gtk-4.0:
    src: config/gtk-4.0
    dst: ~/.config/gtk-4.0
    chmod: "700"
  d_himalaya:
    src: config/himalaya
    dst: ~/.config/himalaya
  d_mako:
    src: config/mako
    dst: ~/.config/mako
  d_rbw:
    src: config/rbw
    dst: ~/.config/rbw
  d_spicetify:
    src: config/spicetify
    dst: ~/.config/spicetify
    chmod: "700"
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_sworkstyle:
    src: config/sworkstyle
    dst: ~/.config/sworkstyle
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_wlogout:
    src: config/wlogout
    dst: ~/.config/wlogout
  d_yay:
    src: config/yay
    dst: ~/.config/yay
  f_userchrome.css:
    src: mozilla/firefox/njvfbwgn.default-release/chrome/userChrome.css
    dst: ~/.mozilla/firefox/njvfbwgn.default-release/chrome/userChrome.css
  d_zfunc:
    src: zfunc
    dst: ~/.zfunc
  d_xkb:
    src: xkb
    dst: ~/.xkb
  d_zshrc.d:
    src: local/zshrc.d
    dst: ~/.local/zshrc.d
  f_001.zsh-config.zsh:
    src: local/zshrc.d/001.zsh-config.zsh
    dst: ~/.local/zshrc.d/001.zsh-config.zsh
  f_002.zinit.zsh:
    src: local/zshrc.d/002.zinit.zsh
    dst: ~/.local/zshrc.d/002.zinit.zsh
  f_002.zshrc.zsh_:
    src: local/zshrc.d/002.zshrc.zsh_
    dst: ~/.local/zshrc.d/002.zshrc.zsh_
  f_003.zinit.zsh_:
    src: local/zshrc.d/003.zinit.zsh_
    dst: ~/.local/zshrc.d/003.zinit.zsh_
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
profiles:
  eliot:
    dotfiles:
      - d_aliases.d
      - d_bashrc.d
      - d_profile.d
      - f_bashrc
      - f_bash_profile
      - f_conkyrc
      - f_config
      - d_i3blocks
      - d_nvim
      - d_ranger
      - f_tmux.conf
      - f_xinitrc
      - f_xresources
  eva:
    dotfiles:
      - d_aliases.d
      - d_bashrc.d
      - d_profile.d
      - f_bashrc
      - f_bash_profile
      - f_config
      - d_nvim
      - f_ipython_config.py
      - d_ranger
      - f_tmux.conf
        # - f_xinitrc
      - f_xmodmap
      - f_gitconfig
      - d_git_template
      - f_tmux.conf.local
      - f_init.vim
      - f_ipython_config.py
      - d_startup
      - f_pdbrc.py
      - f_fonts.conf
      - f_ideavimrc
      - f_bashrc.remote
      - d_alacritty
      - d_tridactyl
      - f_colorscheme
      - d_rofi
      - f_70-synaptics.conf
      - f_pam_env.conf
      - d_alacritty
      - f_coc.vim
      - d_lua
      - f_coc-settings.json
      - f_envrc.default
      - d_direnv
  frankie:
    dotfiles:
      - d_aliases.d
      - d_bashrc.d
      - d_profile.d
      - f_bashrc
      - f_bash_profile
      - f_config
      - d_nvim
      - d_ranger
      - f_tmux.conf
      - f_xinitrc
      - f_xmodmap
      - f_gitconfig
      - d_git_template
      - f_ipython_config.py
  RLYLTPZ198.local:
    dotfiles:
      - d_aliases.d
      - d_bashrc.d
      - d_profile.d
      - f_bashrc
      - f_bash_profile
      - f_init.vim
      - d_nvim
      - f_ipython_config.py
      - f_tmux.conf
      - f_tmux.conf.local
      - f_gitconfig
      - d_git_template
      - d_ranger
      - d_startup
      - d_hooks
      - f_fzf
      - f_fzf.bash
      - f_102.forgit.sh
      - f_ideavimrc
      - f_user.json
      - f_test.json
      - d_ssh
  verena:
    dotfiles:
      - d_aliases.d
      - d_bashrc.d
      - d_profile.d
      - f_bashrc
      - f_bash_profile
      - f_config
      - d_nvim
      - f_ipython_config.py
      - d_ranger
      - f_tmux.conf
      - f_xinitrc
      - f_xmodmap
      - f_gitconfig
      - d_git_template
      - f_tmux.conf.local
      - f_init.vim
      - f_ipython_config.py
      - d_startup
      - f_pdbrc.py
      - f_fonts.conf
      - f_ideavimrc
      - f_bashrc.remote
      - d_tridactyl
      - d_alacritty
      - f_ankirc
      - f_exercism_user.json
      - d_ranger
  fuschia:
    dotfiles:
      - d_aliases.d
      - d_bashrc.d
      - d_profile.d
      - f_bashrc
      - f_bash_profile
      - f_config
      - d_nvim
      - f_ipython_config.py
      - d_ranger
      - f_tmux.conf
      - f_xinitrc
      - f_xmodmap
      - f_gitconfig
      - d_git_template
      - f_tmux.conf.local
      - f_init.vim
      - f_ipython_config.py
      - d_startup
      - f_pdbrc.py
      - f_fonts.conf
      - f_ideavimrc
      - f_bashrc.remote
      - d_alacritty
      - d_tridactyl
      - f_colorscheme
      - d_rofi
  ira:
    dotfiles:
      - d_aliases.d
      - d_bashrc.d
      - d_profile.d
      - f_bashrc
      - f_bash_profile
      - d_nvim
      - f_gitconfig
      - d_ranger
      - f_xmodmap
      - d_alacritty
      - d_wofi
        # - f_config
      - d_nvim
      - f_ipython_config.py
      - f_tmux.conf
      - f_tmux.conf.local
      - d_startup
      - d_ssh
        #   # - f_xinitrc
        # - f_xmodmap
        # - f_gitconfig
        # - d_git_template
        # - f_init.vim
        # - f_pdbrc.py
        # - f_fonts.conf
        # - f_ideavimrc
        # - f_bashrc.remote
      - d_tridactyl
        # - f_colorscheme
      - d_rofi
        # - f_70-synaptics.conf
        # - f_pam_env.conf
        # - f_coc.vim
        # - d_lua
        # - f_coc-settings.json
        # - f_envrc.default
      - d_direnv
      - d_alacritty
      - d_azote
      - d_gh
      - d_gnome-session
      - d_goa-1.0
      - d_gtk-3.0
      - d_gtk-4.0
      - d_himalaya
      - d_mako
      - d_rbw
      # - d_spicetify
      - d_sway
      - d_swaylock
      - d_sworkstyle
      - d_waybar
      - d_wlogout
      - d_yay
      - f_userchrome.css
      - d_zfunc
      - d_xkb
      - d_zshrc.d
      - f_001.zsh-config.zsh
      - f_002.zinit.zsh
      - f_002.zshrc.zsh_
      - f_003.zinit.zsh_
      - f_authorized_keys
      - f_ssh_config
      - f_erik_dev0.pem
      - f_g.pem
      - f_gerrit.pem
      - f_id_ed25519
      - f_id_ed25519.pub
      - f_id_gh_actions
      - f_id_gh_actions.pub
      - f_id_rsa_eva
      - f_id_rsa_eva.pub
      - f_known_hosts
      - f_known_hosts.old
      - f_zeit-app.pem
  lia.local:
    dotfiles:
    - d_aliases.d
    - d_bashrc.d
    - d_profile.d
    - f_bashrc
    - f_bash_profile
    - d_nvim
    - f_gitconfig
    - d_ranger
    - d_alacritty
    - d_nvim
    - f_ipython_config.py
    - f_tmux.conf
    - f_tmux.conf.local
    - d_ssh
    - d_tridactyl
    - d_direnv
    - d_alacritty
    - d_gh
    - d_rbw
    - d_zfunc
