env:
  TERM: xterm-256color
  # history: '10000'

live_config_reload: true

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - tmux attach-session -t main 2> /dev/null || tmux attach-session -t main 2>
      /dev/null ||  tmux new -A -s main
    # - "source ~/.zshrc && tmux attach-session -t main 2> /dev/null || tmux attach-session -t main 2> /dev/null ||  tmux new -A -s main"
  # shell:
  # program: /usr/bin/zellij
  # args:
  # - options --default-shell nu
mouse:
  hide_when_typing: false

font:
  size: 13
  normal:
    family: Victor Mono Nerd Font
    style: Normal
  bold:
    family: Victor Mono Nerd Font
    style: Bold
  italic:
    family: Victor Mono Nerd Font
    style: Light Italic

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

window:
  opacity: 0.9

key_bindings:
  - { key: Return, mods: Control, action: ToggleViMode }
  - { key: V, mods: Alt, action: Paste }
