env:
  TERM: xterm-256color
  # history: '10000'

live_config_reload: true

shell:
  program: bash
  args:
    - -l
    - -c
    - tmux attach-session -t main || tmux attach || tmux

mouse:
  hide_when_typing: true

font:
  size: 12
  normal:
    family: Victor Mono
    style: Light
  bold:
    family: Victor Mono
    style: Bold
  italic:
    family: Victor Mono
    style: Light Italic

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

    # window:
    #   opacity: 1.0

key_bindings:
  - {key: Return, mods: Control, action: ToggleViMode}
  - {key: V, mods: Alt, action: Paste}
colors:
  # COLORSCHEME: gruvbox-dark.yaml
  # Default colors
  primary:
    # hard contrast: background = '0xf9f5d7'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black: '0x282828'
    red: '0xcc241d'
    green: '0x98971a'
    yellow: '0xd79921'
    blue: '0x458588'
    magenta: '0xb16286'
    cyan: '0x689d6a'
    white: '0xa89984'

  # Bright colors
  bright:
    black: '0x928374'
    red: '0xfb4934'
    green: '0xb8bb26'
    yellow: '0xfabd2f'
    blue: '0x83a598'
    magenta: '0xd3869b'
    cyan: '0x8ec07c'
    white: '0xebdbb2'
