font:
  size: 8
  normal:
    family: FiraCode
    style: Regular

  # The bold font face
  bold:
    family: FiraCode
    style: Bold

  # The italic font face
  italic:
    family: FiraCode
    style: Italic

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

background_opacity: 1.0

key_bindings:
  - {key: Return, mods: Control, action: ToggleViMode}
  - {key: V, mods: Alt, action: Paste}
colors:
  # COLORSCHEME: ayu-dark.yaml
  # Default colors
  primary:
    # hard contrast: background = '0xf9f5d7'
    background: '#0A0E14'
    foreground: '#B3B1AD'

  # Normal colors
  normal:
    black: '#01060E'
    red: '#EA6C73'
    green: '#91B362'
    yellow: '#F9AF4F'
    blue: '#53BDFA'
    magenta: '#FAE994'
    cyan: '#90E1C6'
    white: '#C7C7C7'

  # Bright colors
  bright:
    black: '#686868'
    red: '#F07178'
    green: '#C2D94C'
    yellow: '#FFB454'
    blue: '#59C2FF'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'
